import{a as P,S,i as n}from"./assets/vendor-xpOxgMII.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const E="54230749-f3a9f749c9b4d8e3a8cc4a241",q="https://pixabay.com/api/",u=15;async function f(s,t){return(await P.get(q,{params:{key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:u}})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const t=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:r,views:c,comments:w,downloads:v})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${o}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r}</p>
          <p><b>Views</b> ${c}</p>
          <p><b>Comments</b> ${w}</p>
          <p><b>Downloads</b> ${v}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),B.refresh()}function M(){m.innerHTML=""}function p(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}function $(){y.classList.remove("is-hidden")}function d(){y.classList.add("is-hidden")}const A=document.querySelector(".load-more"),b=document.querySelector(".form");b.addEventListener("submit",H);A.addEventListener("click",O);let l="",i=1;async function H(s){if(s.preventDefault(),l=s.target.elements["search-text"].value.trim(),l===""){n.error({title:"Error",message:"Please enter a search query."});return}d(),M(),i=1,p();try{const{data:t}=await f(l,i),o=t.hits;if(o.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}g(o);const a=Math.ceil(t.totalHits/u);i>=a?n.info({title:"Limit reached",message:"We are sorry, but you've reached the end of search results."}):$()}catch(t){console.log(t),n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{L()}b.reset()}async function O(s){d(),i+=1,p();try{const{data:t}=await f(l,i),o=t.hits;g(o);const a=document.querySelector(".gallery-item");if(a){const{height:r}=a.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}const e=Math.ceil(t.totalHits/u);i>=e&&(d(),n.info({title:"Limit reached",message:"We are sorry, but you've reached the end of search results."}))}catch(t){console.log(t),n.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{L()}}
//# sourceMappingURL=index.js.map
