import{a as v,S as q,i as s}from"./assets/vendor-xpOxgMII.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const B="54230749-f3a9f749c9b4d8e3a8cc4a241",M="https://pixabay.com/api/";async function u(o,t){return(await v.get(M,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),$=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:i,largeImageURL:c,tags:e,likes:r,views:a,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${i}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${r}</p>
          <p><b>Views</b> ${a}</p>
          <p><b>Comments</b> ${w}</p>
          <p><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function P(){f.innerHTML=""}function p(){m.classList.remove("is-hidden")}function g(){m.classList.add("is-hidden")}function L(){h.classList.remove("is-hidden")}function b(){h.classList.add("is-hidden")}const O=document.querySelector(".form"),x=document.querySelector(".load-more");let l="",n=1,d=0;O.addEventListener("submit",E);x.addEventListener("click",H);async function E(o){if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),!l){s.error({message:"Please enter a search query"});return}n=1,P(),b(),p();try{const t=await u(l,n);if(d=t.totalHits,t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits),n*15<d?L():s.info({message:"We're sorry, but you've reached the end of search results."})}catch{s.error({message:"Something went wrong"})}finally{g()}}async function H(){n+=1,b(),p();try{const o=await u(l,n);y(o.hits),A(),n*15<d?L():s.info({message:"We're sorry, but you've reached the end of search results."})}catch{s.error({message:"Something went wrong"})}finally{g()}}function A(){var t;const o=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
